2023-07-29 18:07:52,230 INFO    MainThread:81951 [wandb_setup.py:_flush():76] Current SDK version is 0.15.7
2023-07-29 18:07:52,230 INFO    MainThread:81951 [wandb_setup.py:_flush():76] Configure stats pid to 81951
2023-07-29 18:07:52,230 INFO    MainThread:81951 [wandb_setup.py:_flush():76] Loading settings from /Users/vahid/.config/wandb/settings
2023-07-29 18:07:52,230 INFO    MainThread:81951 [wandb_setup.py:_flush():76] Loading settings from /Users/vahid/GitHub/lc_qa_chat/wandb/settings
2023-07-29 18:07:52,230 INFO    MainThread:81951 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2023-07-29 18:07:52,231 INFO    MainThread:81951 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-29 18:07:52,231 INFO    MainThread:81951 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'app.py', 'program': '/Users/vahid/GitHub/lc_qa_chat/app.py'}
2023-07-29 18:07:52,231 INFO    MainThread:81951 [wandb_init.py:_log_setup():507] Logging user logs to /Users/vahid/GitHub/lc_qa_chat/wandb/run-20230729_180752-i9ec7u6h/logs/debug.log
2023-07-29 18:07:52,231 INFO    MainThread:81951 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/vahid/GitHub/lc_qa_chat/wandb/run-20230729_180752-i9ec7u6h/logs/debug-internal.log
2023-07-29 18:07:52,231 INFO    MainThread:81951 [wandb_init.py:init():547] calling init triggers
2023-07-29 18:07:52,231 INFO    MainThread:81951 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-29 18:07:52,231 INFO    MainThread:81951 [wandb_init.py:init():596] starting backend
2023-07-29 18:07:52,231 INFO    MainThread:81951 [wandb_init.py:init():600] setting up manager
2023-07-29 18:07:52,236 INFO    MainThread:81951 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-29 18:07:52,238 INFO    MainThread:81951 [wandb_init.py:init():606] backend started and connected
2023-07-29 18:07:52,247 INFO    MainThread:81951 [wandb_init.py:init():697] updated telemetry
2023-07-29 18:07:52,265 INFO    MainThread:81951 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2023-07-29 18:07:52,563 ERROR   MainThread:81951 [wandb_init.py:init():756] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-29 18:07:52,626 ERROR   MainThread:81951 [wandb_init.py:init():1165] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1147, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/vahid/GitHub/lc_qa_chat/venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 762, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-29 18:07:53,635 WARNING MsgRouterThr:81951 [router.py:message_loop():77] message_loop has been closed
